import time
i = 1000

while i > 0:
    print(f"{i} - 7 = {i-7}")
    i -= 7
    time.sleep(0.1)
if i < 0:
    print("ЗАСКАМИЛ КАК МАМОНТА АХАХАХХАХАХХАХАХХАХАХХАХАХАХХАХАХАХ))))))))000)000)0))))))0))")
    time.sleep(0.5)
    print("                                        ")
    time.sleep(0.5)
    print("                        ,  .            ")
    time.sleep(0.5)
    print("                    # .(%%(/#&. /(,     ")
    time.sleep(0.5)
    print("                * /  (%(#*/#(//*%@@%@ / ")
    time.sleep(0.5)
    print("                (& ((#&,(,*(.&//#@@@@@@,")
    time.sleep(0.5)
    print("                 # /#*/(**.%,/**/(.@@@@ ")
    time.sleep(0.5)
    print("                    (.@(@%.%(/,#.#,(@@@@")
    time.sleep(0.5)
    print("                 *  #,/#,&##@(,( &,,(.%@")
    time.sleep(0.5)
    print("                 ,#(#/,% @,(,/#%/@#,@*@@")
    time.sleep(0.5)
    print("                  @**@ %./**,%@@&## (*@/")
    time.sleep(0.5)
    print("                 &%%%#,(**/#,% @%/%**##/")
    time.sleep(0.5)
    print("                    @#*/(**%,#,/ #%&# .(")
    time.sleep(0.5)
    print("                       ****((& && #     ")
    time.sleep(0.5)
    print("                   *@@@@@@@@@@@@@       ")
    time.sleep(0.5)
    print("                   @@@@@@@@@@@@@@       ")
    time.sleep(0.5)
    print("                 @@@@@@@@@@@@@@@@@      ")
    time.sleep(0.5)
    print("               @@@@@@@@@@@@@&@@@@@@     ")
    time.sleep(0.5)
    print("            @@@@@@@@@@@@@@@@@@@@@@@@    ")
    time.sleep(0.5)
    print("          @@@@@@@@@@@@@@@@@@@@@@@@@@@@  ")
    time.sleep(0.5)
    print("        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ")